apps/career/urls.py
from django.urls import path
from . import views

app_name = 'career'
urlpatterns = [
    path('quarter/', views.quarter_list, name='quarter_list'),
    path('quarter/create/', views.quarter_create, name='quarter_create'),
    path('quarter/<int:q_id>/details/', views.quarter_details, name='quarter_details'),
    path('quarter/<int:q_id>/update/', views.quarter_update, name='quarter_update'),
    path('quarter/<int:q_id>/delete/', views.quarter_delete, name='quarter_delete'),
    
    path('level/', views.LevelListView.as_view(), name='level_list'),
    path('level/create/', views.LevelCreateView.as_view(), name='level_create'),
    path('level/<int:pk>/details/', views.LevelDetailView.as_view(), name='level_details'),
    path('level/<int:pk>/update/', views.LevelUpdateView.as_view(), name='level_update'),
    path('level/<int:pk>/delete/', views.LevelDeleteView.as_view(), name='level_delete'),
    
    path('career/', views.CareerListView.as_view(), name='career_list'),
    path('career/create/', views.CareerCreateView.as_view(), name='career_create'),
    path('career/<int:pk>/details/', views.CareerDetailView.as_view(), name='career_details'),
    path('career/<int:pk>/update/', views.CareerUpdateView.as_view(), name='career_update'),
    path('career/<int:pk>/delete/', views.CareerDeleteView.as_view(), name='career_delete'),
    
    path('<int:career_id>/subject', views.SubjectListView.as_view(), name='subject_list'),
    path('<int:career_id>/subject/create/', views.SubjectCreateView.as_view(), name='subject_create'),
    path('<int:career_id>/subject/<int:pk>/update/', views.SubjectUpdateView.as_view(), name='subject_update'),
    # path('subject/<int:pk>/details/', views.SubjectDetailView.as_view(), name='subject_details'),
    # path('subject/<int:pk>/delete/', views.SubjectDeleteView.as_view(), name='subject_delete'),
]

siiut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('career/', include('apps.career.urls')),
    path('accounts/',  include('django.contrib.auth.urls')),
]

apps/career/models.py
from django.db import models
from django.contrib.auth.models import User

class Quarter(models.Model):
    quarter = models.IntegerField(verbose_name='Cuatrimestre No.')
    quarter_name = models.CharField(verbose_name='Cuatrimestre', max_length=25)
    
    def __str__(self):
        return self.quarter_name
    
    class Meta:
        verbose_name = 'Cuatrimestre'
        verbose_name_plural = 'Cuatrimestres'
        
class Level(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nivel')
    short_name = models.CharField(max_length=10,verbose_name='Nombre corto')
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Nivel'
        verbose_name_plural = 'Niveles'

class Career(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')
    short_name = models.CharField(max_length=10,verbose_name='Nombre corto')
    level = models.ForeignKey(Level, on_delete=models.CASCADE, null = True, blank=True,verbose_name='Nivel',related_name='careers')
    is_active = models.BooleanField(verbose_name='Activo', default=True)
    principal = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,related_name='careers', verbose_name='Director')
    year = models.CharField(max_length=5,verbose_name='Año')
    
    def __str__(self):
        return f"{self.level} - {self.name}"
    
    class Meta:
        verbose_name = 'Carrera'

class Subject(models.Model):
    career = models.ForeignKey(Career, verbose_name='Carrera', on_delete=models.CASCADE, related_name='subjects')
    quarter = models.ForeignKey(Quarter, verbose_name='Cuatrimestre', on_delete=models.CASCADE, related_name='subjects')
    name = models.CharField(max_length=100, verbose_name="Materia")
    total_hours = models.IntegerField(verbose_name='Horas totales')
    weekly_hours = models.IntegerField(verbose_name='Horas por semana')
    # file: para guardar la hoja de asignatura
    
    def __str__(self):
        return f"{self.career.short_name} - {self.quarter} - {self.name}"
    
    class Meta:
        verbose_name = 'Materia'
    

apps/career/forms.py
from django import forms
from .models import Quarter, Level, Career, Subject

input_class = 'border border-gray-400 p-1 rounded-xl mt-2'

class QuarterForm(forms.ModelForm):
    class Meta:
        model = Quarter
        fields = ['quarter', 'quarter_name']
        widgets = {
            'quarter': forms.TextInput(attrs={'type':'number','class': input_class}),
            'quarter_name': forms.TextInput(attrs={'class': input_class})
        }
        
class LevelForm(forms.ModelForm):
    class Meta:
        model = Level
        fields = ['name', 'short_name']
        widgets = {
            'name': forms.TextInput(attrs={'class':input_class}),
            'short_name': forms.TextInput(attrs={'class':input_class})
        }
        
class CareerForm(forms.ModelForm):
    class Meta:
        model = Career
        fields = ['name', 'short_name', 'level', 'is_active', 'principal', 'year']
        widgets = {
            'name': forms.TextInput(attrs={'class':input_class}),
            'short_name': forms.TextInput(attrs={'class':input_class}),
            'level': forms.Select(attrs={'class':input_class}),
            'is_active': forms.CheckboxInput(attrs={'class':input_class}),
            'principal': forms.Select(attrs={'class':input_class}),
            'year': forms.TextInput(attrs={'class':input_class})
        }
        
class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['quarter', 'name', 'total_hours', 'weekly_hours']
        widgets = {
            # 'career': forms.Select(attrs={'class':input_class}),
            'quarter': forms.Select(attrs={'class':input_class}),
            'name': forms.TextInput(attrs={'class':input_class}),
            'total_hours': forms.TextInput(attrs={'class':input_class}),
            'weekly_hours': forms.TextInput(attrs={'class':input_class})
        }

apps/career/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import QuarterForm, LevelForm, CareerForm, SubjectForm
from .models import Quarter, Level, Career, Subject

# CRUD Views for Quarter
#---------------------------------------------------------------------------------------------------

def quarter_list(request):
    quarters = Quarter.objects.all()
    context = {
        "quarters": quarters
    }
    return render(request, 'career/quarter/index.html', context)

def quarter_create(request):
    if request.method == 'POST':
        form = QuarterForm(request.POST)
        if form.is_valid():
            quarter = Quarter(
                quarter=form.cleaned_data['quarter'],
                quarter_name=form.cleaned_data['quarter_name']
            )
            quarter.save()
            return redirect('career:quarter_list')
    else:
        form = QuarterForm()
        return render(request, 'career/quarter/create.html', {'form': form})
    
def quarter_details(request, q_id):
    quarter = Quarter.objects.get(pk=q_id)
    return render(request, 
                  'career/quarter/details.html',
                  {'quarter': quarter})
    
def quarter_update(request, q_id):
    q = Quarter.objects.get(pk=q_id)
    if request.method == 'POST':
        form = QuarterForm(request.POST)
        if form.is_valid():
            q.quarter = form.cleaned_data['quarter']
            q.quarter_name = form.cleaned_data['quarter_name']
            q.save()
            return redirect('career:quarter_list')
        else:
            return HttpResponse('Hay error en el formulario')
    else:
        form = QuarterForm(instance=q)
        return render(request, 
                    'career/quarter/update.html',
                    {'form': form})
        
def quarter_delete(request, q_id):
    if request.method == 'POST':
        q = Quarter.objects.get(pk=q_id)
        q.delete()
        return redirect('career:quarter_list')
    
#---------------------------------------------------------------------------------------------------
# Vistas basadas en clases para level model
class LevelListView(ListView):
    model = Level
    template_name = 'career/level/index.html'
    context_object_name = 'levels'
    
class LevelDetailView(DetailView):
    model = Level
    template_name = 'career/level/details.html'
    context_object_name = 'level'
    
class LevelCreateView(CreateView):
    model = Level
    form_class = LevelForm
    template_name = 'career/level/create.html'
    success_url = reverse_lazy('career:level_list')
    
class LevelUpdateView(UpdateView):
    model = Level
    form_class = LevelForm
    template_name = 'career/level/update.html'
    success_url = reverse_lazy('career:level_list')

class LevelDeleteView(DeleteView):
    model = Level
    template_name = 'career/level/delete.html'
    success_url = reverse_lazy('career:level_list')

#---------------------------------------------------------------------------------------------------
# Vistas basadas en clases para career model
class CareerListView(ListView):
    model = Career
    template_name = 'career/career/index.html'
    context_object_name = 'careers'
    
class CareerDetailView(DetailView):
    model = Career
    template_name = 'career/career/details.html'
    context_object_name = 'career'
    
class CareerCreateView(CreateView):
    model = Career
    form_class = CareerForm
    template_name = 'career/career/create.html'
    success_url = reverse_lazy('career:career_list')
    
class CareerUpdateView(UpdateView):
    model = Career
    form_class = CareerForm
    template_name = 'career/career/update.html'
    success_url = reverse_lazy('career:career_list')
    
class CareerDeleteView(DeleteView):
    model = Career
    template_name = 'career/career/delete.html'
    success_url = reverse_lazy('career:career_list')
    
#---------------------------------------------------------------------------------------------------
# Vistas basadas en clases para subject model
class SubjectListView(ListView):
    model = Subject
    paginate_by = 10
    template_name = 'career/subject/index.html'
    context_object_name = 'subjects'
    
    def get_queryset(self):
        queryset = super().get_queryset()
        id_career = self.kwargs.get('career_id')
        queryset = queryset.filter(career_id=id_career).order_by('quarter', 'name')
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_career = self.kwargs.get('career_id')
        context['career'] = Career.objects.get(pk=id_career)
        return context
    
class SubjectCreateView(CreateView):
    model = Subject
    form_class = SubjectForm
    template_name = 'career/subject/create.html'
    success_url = reverse_lazy('career:subject_list')
    
    def form_valid(self, form):
        id_career = self.kwargs.get('career_id')
        career = Career.objects.get(id=id_career)
        form.instance.career = career
        return super().form_valid(form)

    def get_success_url(self):
        id_career = self.kwargs.get('career_id')
        return reverse_lazy('career:subject_list', kwargs={'career_id': id_career})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_career = self.kwargs.get('career_id')
        context['career'] = Career.objects.get(pk=id_career)
        return context
                
class SubjectUpdateView(UpdateView):
    model = Subject
    form_class = SubjectForm
    template_name = 'career/subject/update.html'
    # success_url = reverse_lazy('career:subject_list')
    
    def get_success_url(self):
        id_career = self.kwargs.get('career_id')
        return reverse_lazy('career:subject_list', kwargs={'career_id': id_career})
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_career = self.kwargs.get('career_id')
        context['career'] = Career.objects.get(pk=id_career)
        return context

# class SubjectDetailView(DetailView):
#     model = Subject
#     template_name = 'career/subject/details.html'
#     context_object_name = 'subject'
    
# class SubjectDeleteView(DeleteView):
#     model = Subject
#     template_name = 'career/subject/delete.html'
#     success_url = reverse_lazy('career:subject_list')

templates/career/quarter/create.html
{% extends 'base.html' %} {% block title %} Lista de Cuatrimestres {% endblock title %} 
{% block content %}

<h1 class="text-2xl truncate">Nuevo Cuatrimestre</h1>
<form method="post">
  {% csrf_token %} {{ form }}
  <input
    class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 mt-2 border border-gray-400 rounded shadow"
    type="submit"
    value="Guardar"
  />
</form>
{% endblock content %}

templates/career/quarter/details.html
{% extends 'base.html' %} {% block title %} Detalles de Cuatrimestres {% endblock title %} 
{% block content %}
<h1 class="text-2xl truncate">Detalles de Cuatrimestre</h1>
<div>
  <p class="text-2xl">Grado: {{ quarter.quarter }}°</p>
  <p class="text-2xl">Nombre: {{ quarter.quarter_name }}</p>
  <br>
  <a class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" href="{% url 'career:quarter_update' quarter.id %}">Actualizar</a>

  <form action="{% url 'career:quarter_delete' quarter.id %}" method="post">
    {% csrf_token %}
    <br>
    <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" type="submit" onclick="confirm('Seguro?')">Eliminar</button>

  </form>
  <br>
  <a class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" href="{% url 'career:quarter_list' %}">Regresar</a>
</div>

{% endblock content %}

templates/career/quarter/index.html
{% extends 'base.html' %} 

{% block title %} Lista de Cuatrimestres {% endblock title %} 

{% block content %}
<h1 class="text-2xl text-purple-700 font-bold">Cuatrimestres</h1>
<br>
<a 
  class="bg-purple-300 hover:bg-purple-400 text-black font-semibold py-2 px-4 border border-purple-500 rounded shadow" 
  href="{% url 'career:quarter_create' %}">Nuevo Cuatri</a>
<br>
<table class="border-collapse border border-purple-500 w-full mt-4 bg-transparent">
  <thead>
    <tr class="bg-gray-400 text-black">
      <th class="border border-purple-500 p-2">Id</th> 
      <th class="border border-purple-500 p-2">Cuatrimestre No.</th>
      <th class="border border-purple-500 p-2">Cuatrimestre</th>
      <th class="border border-purple-500 p-2">Acciones</th>
    </tr>
  </thead>
  <tbody>
    {% for quarter in quarters %}
    <tr class="bg-transparent hover:bg-purple-200">
      <td class="border text-center border-purple-400 p-2">{{quarter.id}}</td>
      <td class="border text-center border-purple-400 p-2">{{quarter.quarter}}</td>
      <td class="border text-center border-purple-400 p-2">{{quarter.quarter_name}}</td>
      <td class="border text-center border-purple-400 p-2">
        <a class="text-purple-700 hover:underline" href="{% url 'career:quarter_details' quarter.id %}">Detalles</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

templates/career/quarter/update.html
{% extends 'base.html' %}

{% block title %}
    Actualizar Cuatrimestre
{% endblock title %}

{% block content %}
<h1 class="text-2xl truncate">Actualizar Cuatrimestre</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input 
    class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 mt-2 border border-gray-400 rounded shadow"
    type="submit" value="Actualizar" 
    />
</form>
{% endblock content %}