apps/career/urls.py
from django.urls import path
from . import views

app_name = 'career'
urlpatterns = [
    path('quarter/', views.quarter_list, name='quarter_list'),
    path('quarter/create/', views.quarter_create, name='quarter_create'),
    path('quarter/<int:q_id>/details/', views.quarter_details, name='quarter_details'),
    path('quarter/<int:q_id>/update/', views.quarter_update, name='quarter_update'),
    path('quarter/<int:q_id>/delete/', views.quarter_delete, name='quarter_delete'),
    
    path('level/', views.LevelListView.as_view(), name='level_list'),
    path('level/create/', views.LevelCreateView.as_view(), name='level_create'),
    path('level/<int:pk>/details/', views.LevelDetailView.as_view(), name='level_details'),
    path('level/<int:pk>/update/', views.LevelUpdateView.as_view(), name='level_update'),
    path('level/<int:pk>/delete/', views.LevelDeleteView.as_view(), name='level_delete'),
    
    path('career/', views.CareerListView.as_view(), name='career_list'),
    path('career/create/', views.CareerCreateView.as_view(), name='career_create'),
    path('career/<int:pk>/details/', views.CareerDetailView.as_view(), name='career_details'),
    path('career/<int:pk>/update/', views.CareerUpdateView.as_view(), name='career_update'),
    path('career/<int:pk>/delete/', views.CareerDeleteView.as_view(), name='career_delete'),
    
    path('<int:career_id>/subject', views.SubjectListView.as_view(), name='subject_list'),
    path('<int:career_id>/subject/create/', views.SubjectCreateView.as_view(), name='subject_create'),
    path('<int:career_id>/subject/<int:pk>/update/', views.SubjectUpdateView.as_view(), name='subject_update'),
    # path('subject/<int:pk>/details/', views.SubjectDetailView.as_view(), name='subject_details'),
    # path('subject/<int:pk>/delete/', views.SubjectDeleteView.as_view(), name='subject_delete'),
]

apps/home/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

siiut/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('career/', include('apps.career.urls')),
    path('accounts/',  include('django.contrib.auth.urls')),
]

templates/shared/header.html
<header class="bg-slate-500 text-white">
    <nav class="container mx-auto flex items-center justify-between py-4">
        <a href="" class="text-lg font-bold">SIIUT</a>
        <ul class="flex space-x-4">
            
            {% if user.is_authenticated %}
            <li>
                <form method="post" action="{% url 'home:logout' %}">
                    {% csrf_token %}
                    <input type="submit" value="Salir">
                </form>
            </li>
            {% else %}
            <li>
                <a href="{% url 'home:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/shared/menu.html
<nav>
  <ul>
    <li>
      <a
        class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-md p-2"
        href="{% url 'home:home' %}">
        Home
      </a>
    </li>
    <li>
      <a
        class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-md p-2"
        href="{% url 'home:about' %}">
        Acerca de
      </a>
    </li>
    <li>
      <a
        class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-md p-2"
        href="{% url 'home:contact' %}">
        Contacto
      </a>
    </li>
    
    {% if user.is_authenticated %}      
    <li>
      <a
        class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-md p-2"
        href="{% url 'career:quarter_list' %}">
        Cuatrimestres
      </a>
    </li>
    <li>
      <a
        class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-md p-2"
        href="{% url 'career:level_list' %}">
        Niveles
      </a>
    </li>
    <li>
      <a
        class="block w-[200px] bg-slate-200 hover:bg-slate-400 m-2 rounded-md p-2"
        href="{% url 'career:career_list' %}">
        Carreras
      </a>
    </li>
    {% endif %}
  </ul>
</nav>